### ISSUE TITLE
支持同时采集多个直播间吗

### ISSUE THREAD

**Issue by BB-9E** [Passkou/BiliLiveDanmaku#1]
大佬,这个支持同时采集多个直播间吗?还是只能开多线程搞?

**Comment by Passkou** [comment]
我没考虑过同时连接多个直播间的2333，主要是可以给来当弹幕姬用（点歌等功能）
如果要多个直播间，可能多线程解决不了问题。。要多进程。或者你也可以稍微改造一下代码就可以用了

**Comment by BB-9E** [comment]
> 我没考虑过同时连接多个直播间的2333，主要是可以给来当弹幕姬用（点歌等功能）
> 如果要多个直播间，用多线程应该就可以了，因为连接直播间后会被双重。

**Comment by BB-9E** [comment]
谢谢大佬,我再研究研究
